[build]
  base = "/opt/build/repo/server"
  publish = "/opt/build/repo/server"
  command = "dotnet build && dotnet publish -o /opt/build/repo/server/publish"

[build.environment]
  DOTNET_VERSION = "8.0.0"

[[plugins]]
  package = "@netlify/plugin-dotnet"

[[plugins.inputs]]
  command = "install"
  args = ["8.0.0"]

[[plugins.inputs]]
  command = "dotnet build && dotnet publish -o /opt/build/repo/server/publish"
s